# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15f736340716ff8cb273d5bea1b5736bdce9b142f7d0e69ad117bee4ba09d65306f465b5165eb587694af69925a255d177e4e405f2eed0aa8350390460b5b208

test:
  secret_key_base: dce7cc20607e77e328ec84bd23f14247cbde2853ef8809892cfc757910b2b5682c68715c1ed26c8c6bbe792fcc88d7b38394629a8754d42be8170caa36c618f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
